---
routes:

    #########################################################
    # STOR / NODES                                          #
    #########################################################

    be_stor:
        service:    stor
        path:       /api/stor
        pattern:    /api/stor
        label:      stor
        dscr:       A routegroup, no methods here.

    #########################################################
    # STOR / HEALTH                                         #
    #########################################################

    be_stor_health_v1:
        pattern:    ${routes.be_stor.path}/v1/health
        path:       ${routes.be_stor.path}/v1/health
        label:      stor health
        dscr:       A healthcheck endpoint for the microservice.
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:health



    #########################################################
    # STOR / BUCKETS                                        #
    #########################################################

    be_stor_devices_v1:
        pattern:    ${routes.be_stor.path}/v1/devices[/{id}]
        path:       ${routes.be_stor.path}/v1/devices
        label:      Storage devices
        dscr:       Storage devices (physical disks, remote service storage buckets)
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:devices_r1

    be_stor_dgs_v1:
        pattern:    ${routes.be_stor.path}/v1/dgs[/{id}]
        path:       ${routes.be_stor.path}/v1/dgs
        label:      Device groups
        dscr:       Logical groups of storage devices
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:dgs_r1

    be_stor_objects_v1:
        pattern:    ${routes.be_stor.path}/v1/buckets/{bucket}/objects[/{object}[/{method}]]
        path:       ${routes.be_stor.path}/v1/buckets
        label:      objects
        dscr:       Data objects
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:objects_r1
            post:   Glued\Controllers\ServiceController:objects_c1
            patch:  Glued\Controllers\ServiceController:objects_p1
            delete: Glued\Controllers\ServiceController:objects_d1
            put:    Glued\Controllers\ServiceController:objects_put1

    be_stor_buckets_v1:
        pattern:    ${routes.be_stor.path}/v1/buckets[/{id}]
        path:       ${routes.be_stor.path}/v1/buckets
        label:      Buckets
        dscr:       Isolated data buckets
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:buckets_r1
            post:   Glued\Controllers\ServiceController:buckets_c1

    #########################################################
    # STOR / OBJECTS                                        #
    #########################################################




    #########################################################
    # STOR / LINKS                                          #
    #########################################################

    be_stor_links_v1:
        pattern:    ${routes.be_stor.path}/v1/links/{token}/{nonce}/{exp}
        path:       ${routes.be_stor.path}/v1/links
        label:      links
        dscr:       File links
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:links_r1
