---
routes:

    #########################################################
    # STOR / NODES                                          #
    #########################################################

    be_stor:
        service:    stor
        path:       /api/stor
        pattern:    /api/stor
        label:      stor
        dscr:       A routegroup, no methods here.

    #########################################################
    # STOR / HEALTH                                         #
    #########################################################

    be_stor_health_v1:
        pattern:    ${routes.be_stor.path}/health/v1
        path:       ${routes.be_stor.path}/health/v1
        label:      stor health
        dscr:       A healthcheck endpoint for the microservice.
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:health

    be_stor_health_dgs_v1:
        pattern:    ${routes.be_stor.path}/health/dgs/v1[/{uuid}]
        path:       ${routes.be_stor.path}/health/dgs/v1
        label:      stor health
        dscr:       A healthcheck endpoint for the microservice.
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:healthDgs


    #########################################################
    # STOR / BUCKETS                                        #
    #########################################################

    be_stor_buckets_v1:
        pattern:    ${routes.be_stor.path}/buckets/v1
        path:       ${routes.be_stor.path}/buckets/v1
        label:      Buckets
        dscr:       Isolated data buckets
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:buckets_r1
            post:   Glued\Controllers\ServiceController:buckets_c1

    #########################################################
    # STOR / OBJECTS                                        #
    #########################################################

    be_stor_objects_v1:
        pattern:    ${routes.be_stor.path}/objects/v1[/{bucket}[/{object}]]
        path:       ${routes.be_stor.path}/objects/v1
        label:      objects
        dscr:       Data objects
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:objects_r1
            post:   Glued\Controllers\ServiceController:objects_c1


    #########################################################
    # STOR / LINKS                                          #
    #########################################################

    be_stor_links_v1:
        pattern:    ${routes.be_stor.path}/links/v1[/{bucket}[/{link}]]
        path:       ${routes.be_stor.path}/links/v1
        label:      links
        dscr:       File links
        service:    stor
        methods:
            get:    Glued\Controllers\ServiceController:links_r1
            post:   Glued\Controllers\ServiceController:links_c1
            patch:  Glued\Controllers\ServiceController:links_u1
            delete: Glued\Controllers\ServiceController:links_d1